apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app

spec:
  containers:
    - name: result-app
      image: danishdd/voting_result_app:latest
      ports:
        - containerPort: 80
      env:
        - name: MONGO_HOST
          value: "mongo-service"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DATABASE
          value: "Votes_Server"
          
        # - name: SERVICE_DB_URL
        #   value: mongodb://mongo-service:27017/?authSource=admin&retryWrites=false
        # - name: SERVICE_DB
        #   value: Votes_Server
